### PR TITLE
Add new character and new recruitment tags

### PR DESCRIPTION
**Pull request by C0unt-zero**
# new characters
"121": "Sage Shiro"
"506": "Elegance Personified Salucia"
"507": "Dragon Dancer Lana"
"508": "Sweet Cocoa Ba'al"
"509": "Pure Cocoa Iblis"
"510": "Killer Cocoa Satan"

# recruitment tags
## Tags to include in the update
| Character  | Tags|
| ------------- | ------------- |
|Ancient Hero Uruta（古代勇者 烏魯塔）| 23 : Defense（防禦）\| 29 : Survivability（生存力） |
|Future Hero Muila（未來勇者 牧愛菈）| 26 : Support（支援） |
|Enchantress Anjelica （千咒魔女 安西莉卡）| 30 : More Power（越戰越強）|
|Magic Automaton KS-Ⅷ （魔人偶 KS-Ⅷ）| 30 : More Power（越戰越強）|
|Dwarf Queen Lana（矮人王 蘭兒）| 30 : More Power（越戰越強）|
|Fallen Dragon Karina（墮龍 凱茜菲）| 17 : Giant Tits（巨乳）|
|Health Nut Lotus（元氣補給 蓮）|14 : Medium Sized（中體型）|

### remove
| Character  | Tags|
| ------------- | ------------- |
|Foreign Merchant Sherana（異國商人 雪蘭瑚）|14 : Medium Sized（中體型）|

### CODE REVIEW

**Comment by C0unt-zero** [comment]
@purindaisuki I would like to change the id of Usagihime from 500 to 1000, but simply changing it may corrupt the data containing Usagihime submitted to Team compositions.
Is there a way to correct the submitted data?

07a819695935ec7c697319f34ceff8c59e73af85

I added the above commit and tested it, but it is inconsistent and freezes because the data containing past UsagiHime is posted on the Team compositions server.

https://c0unt-zero.github.io/tkfmtools/en/team/

**Comment by purindaisuki** [comment]
Sorry for the late reply. Given that the data is also saved in users' localStorage, we need to write some code to handle the data if we want to change the id. Could you please provide more information on why you want to make this change? Some logic depends on the first number of the id (yeah I know it's a bad design), which could lead to issues. If that's your concern, we could explore a direct fix to this part of the code.

**Comment by C0unt-zero** [comment]
@purindaisuki 
## Current character id rule
| rerity  | id|
| ------------- | ------------- |
|SSR| 1xx|
|SR |2xx|
|R |3xx|
|N| 4xx|

These are named after the last two digits of the file name.
A certain problem occurred due to a change in the asset file naming convention.
That's the problem with duplicate ids when configured according to the rules.

| id (last two digits)  | Character|
| ------------- | ------------- |
|00| Evil Archdemon Usagihime| 
|06| Elegance Personified Salucia|
|07| Dragon Dancer Lana|
|08| Sweet Cocoa Ba'al|
|09|Pure Cocoa Iblis|
|10| Killer Cocoa Satan|

When I set the id as per the previous rule, I had no choice but to move the character id to number 5xx because of the duplicate id, but when I set it to number 5xx, the following problem occurred.

<details>
<summary>Characters with id set to 5xx are not displayed in the potential calculator.</summary>

## When the id is set to 5xx

p500

## When the id is set to 10xx

p1000

</details>

<details>
<summary> The character set at number 5xx can only choose the fifth level of evolution in Team compositions.</summary>

## When the id is set to 5xx



## When the id is set to 10xx



</details>


So I changed the id from 5xx to 10xx and it worked fine, so I was about to change it.

https://github.com/purindaisuki/tkfmtools/blob/4818fb045c698a08ee09213f1683c20341db2c98/src/data/string/character_zh-TW.json#L10-L11
Another idea was to ignore the naming convention and place these characters since 109~116 are open, but I decided against it because the order would be messed up.

**Comment by purindaisuki** [comment]
Hi, I decoupled the rarity from the id so that we can maintain the naming convention. Please let me know if I missed anything or if you have any thoughts.

**Comment by C0unt-zero** [comment]
@purindaisuki I checked and found that the line-up analysis was broken and the gatsby build failed, but everything else I checked with gatsby develop seems fine.

**Comment by purindaisuki** [comment]
Should be fixed. Thanks for pointing it out.

**Comment by C0unt-zero** [comment]
@purindaisuki
Thanks to this, we have finished the whole process.
If there are no problems, they can be merged.

**Pull request merged**
